# Generated by Django 4.1 on 2022-08-26 05:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True, default=None)),
                ("year", models.IntegerField(default=None)),
                ("genre", models.TextField()),
                ("plot", models.TextField()),
                ("imdb_rating", models.IntegerField(default=None)),
                ("rotten_tomatoes", models.IntegerField(default=None)),
                ("torrent_720p", models.TextField()),
                ("torrent_1080p", models.TextField()),
                ("subtitles", models.TextField()),
                ("images", jsonfield.fields.JSONField()),
                ("cast", jsonfield.fields.JSONField()),
            ],
        ),
    ]
