# Generated by Django 4.1 on 2022-08-26 06:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0003_alter_movies_imdb_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="cast",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
        migrations.AlterField(
            model_name="movies",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
    ]
