# Generated by Django 4.1 on 2022-08-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_alter_movies_cast_alter_movies_images"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="movies",
            constraint=models.UniqueConstraint(
                fields=("name", "year"), name="movies_pkey"
            ),
        ),
    ]
