# Generated by Django 4.0.1 on 2022-08-26 06:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_movies_movies_pkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdb_rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rotten_rating',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='subtitles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='torrent_1080p',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='torrent_720p',
            field=models.TextField(null=True),
        ),
    ]
